apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "reportService.fullname" . }}
  labels:
    {{- include "reportService.labels" . | nindent 4 }}
spec:
  schedule: "0 1 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Values.cronjob.containerName }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: {{ include "reportService.image" . | quote }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: MONGODB_CONNECTION_STRING
              value: {{ include "reportService.connection_string" . }}
            {{- if .Values.appSecret }}
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appSecret }}
                  key: jwtSecret
            {{- end }}
            - name: EXECUTION_MODE
              value: {{ .Values.cronjob.executionMode }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}