apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportService.fullname" . }}
  labels:
    {{- include "reportService.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reportService.selectorLabels" . | nindent 4 }}
