nameOverride: ""
fullnameOverride: ""

ingress:
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
    # - host: cad.local
  tls: []
  #  - secretName: tenant-tls
  #    hosts:
  #      - cad.local

appSecret:
  create: true
  name: budget-tracker
  jwtSecret: "changeme"

mongodb:
  fullnameOverride: mongodb
  auth:
    enabled: false

authentication-service:
  fullnameOverride: authentication-service
  db:
    host: mongodb
    collection: authentication
  appSecret: budget-tracker
  tenantServiceUrl: tenant-service
  host: ""

tenant-service:
  fullnameOverride: tenant-service
  db: 
    host: mongodb
    collection: tenants
  appSecret: budget-tracker
  host: ""
  storage:
    connectionString: ""
    containerName: ""

frontend:
  fullnameOverride: frontend

start-page:
  fullnameOverride: start-page

loki-stack:
  loki:
    enabled: true
  promtail:
    enabled: true
