# Default values for budget-tracker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
    # - host: cad.local
  tls: []
  #  - secretName: tenant-tls
  #    hosts:
  #      - cad.local

appSecret:
  create: true
  name: budget-tracker
  jwtSecret: "changeme"

mongodb:
  fullnameOverride: mongodb
  auth:
    enabled: false

authentication-service:
  fullnameOverride: authentication-service
  db:
    internalEnabled: false
    host: mongodb
    collection: authentication
  appSecret: budget-tracker
  tenantServiceUrl: tenant-service

tenant-service:
  fullnameOverride: tenant-service
  db:
    internalEnabled: false
    host: mongodb
    collection: tenants
  appSecret: budget-tracker
  kubernetes:
    client_certificate: ""
    kubernetes_config: ""

frontend:
  fullnameOverride: frontend
