nameOverride: ""
fullnameOverride: ""

ingress:
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx

appSecret:
  create: true
  name: budget-tracker
  jwtSecret: "changeme"

mongodb:
  fullnameOverride: mongodb
  auth:
    enabled: false

authentication-service:
  fullnameOverride: authentication-service
  db:
    host: mongodb
    collection: authentication
  appSecret: budget-tracker
  tenantServiceUrl: http://tenant-service
  host: ""

tenant-service:
  fullnameOverride: tenant-service
  db: 
    host: mongodb
    collection: tenants
  appSecret: budget-tracker
  host: ""
  storage:
    connectionString: ""
    containerName: ""

frontend:
  fullnameOverride: frontend

start-page:
  fullnameOverride: start-page

loki-stack:
  loki:
    enabled: true
    serviceName: loki-stack
  promtail:
    enabled: true
    config:
      clients:
        - url: http://loki-stack:3100/loki/api/v1/push
