nameOverride: ""
fullnameOverride: ""

ingress:
  className: ""
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    # email: "<your_email>"
  annotations: 
    kubernetes.io/ingress.class: nginx

cert-manager:
  installCRDs: "true"

appSecret:
  create: true
  name: budget-tracker
  jwtSecret: "changeme"

mongodb:
  fullnameOverride: mongodb
  auth:
    enabled: false

authentication-service:
  fullnameOverride: authentication-service
  db:
    host: mongodb
    collection: authentication
  appSecret: budget-tracker
  tenantServiceUrl: http://tenant-service
  host: ""

tenant-service:
  fullnameOverride: tenant-service
  db: 
    host: mongodb
    collection: tenants
  appSecret: budget-tracker
  host: ""
  storage:
    connectionString: ""
    containerName: ""

frontend:
  fullnameOverride: frontend

start-page:
  fullnameOverride: start-page

loki-stack:
  loki:
    enabled: true
    fullnameOverride: "loki" 
    serviceName: loki
  promtail:
    enabled: true
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push
