apiVersion: v2
name: transaction-service
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
- name: mongodb
  version: 13.6.*
  repository: "https://charts.bitnami.com/bitnami"
  condition: db.internalEnabled
