apiVersion: v1
kind: Service
metadata:
  name: {{ include "authenticationService.fullname" . }}
  labels:
    {{- include "authenticationService.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port:   {{ .Values.service.port | quote }}
    prometheus.io/path: "/swagger-stats/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "authenticationService.selectorLabels" . | nindent 4 }}
