apiVersion: v2
name: tenant
description: This is the helm chart which deploys the infrastructure of the individual tenants including the free and standard tier

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
- name: transaction-service
  version: "0.1.0"
  repository: "file://../transaction-service"
- name: report-service
  version: "0.1.0"
  repository: "file://../report-service"
- name: mongodb
  version: 13.6.*
  repository: "https://charts.bitnami.com/bitnami"
