nameOverride: ""
fullnameOverride: ""

service:
  type: ExternalName
  port: 80

ingress:
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx

tenantSecret:
  create: true
  name: tenant

frontendService: {}

authenticationService: {}

mongodb:
  fullnameOverride: mongodb
  auth:
    enabled: false

transaction-service:
  fullnameOverride: transaction-service
  db:
    host: mongodb
  tenantSecret: tenant
  storage:
    connectionString: ""
    containerName: ""

report-service:
  fullnameOverride: report-service
  db:
    host: mongodb
  tenantSecret: tenant
  transactionServiceUrl: http://transaction-service
