global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'authentication_service'
    static_configs:
      - targets: ['authentication_service:4000']
    metrics_path: '/swagger-stats/metrics'

  - job_name: 'tenant_service'
    static_configs:
      - targets: ['tenant_service:4000']
    metrics_path: '/swagger-stats/metrics'

  - job_name: 'transaction_service'
    static_configs:
      - targets: ['transaction_service:4000']
    metrics_path: '/swagger-stats/metrics'
