apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transactionService.fullname" . }}
  labels:
    {{- include "transactionService.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/swagger-stats/metrics"
    {{- with .Values.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "transactionService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/swagger-stats/metrics"
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "transactionService.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "transactionService.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: MONGODB_CONNECTION_STRING
              value: {{ include "transactionService.connection_string" . }}
            - name: AZURE_BLOB_STORAGE_CONNECTION_STRING
              value: {{ .Values.storage.connectionString }}
            - name: AZURE_BLOB_STORAGE_CONTAINER_NAME
              value: {{ .Values.storage.containerName }}
            {{- if .Values.tenantSecret }}
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tenantSecret }}
                  key: jwtSecret
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
