apiVersion: v1
kind: Service
metadata:
  name: {{ include "transactionService.fullname" . }}
  labels:
    {{- include "transactionService.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transactionService.selectorLabels" . | nindent 4 }}
