{
 "title": "Budget-Tracker_Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Transaction Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"transaction-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Authentication Service Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"cad/authentication-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Tenant Service Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"cad/tenant-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Report Service",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"report-service\"} |= ``"
    }
   ]
  }
 ]
}