apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  labels:
    {{- include "budgetTracker.labelsIssuer" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.ingress.acme.email }}
    server: {{ .Values.ingress.acme.server  }}
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
