{{- if .Values.appSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "budgetTracker.secretName" . }}
type: Opaque
data:
  jwtSecret: {{ .Values.appSecret.jwtSecret }}
{{- end -}}