{{- if .Values.appSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "budgetTracker.secretName" . }}
  labels:
    {{- include "budgetTracker.labels" . | nindent 4 }}
type: Opaque
data:
  jwtSecret: {{ .Values.appSecret.jwtSecret | b64enc | quote }}
{{- end -}}