replicaCount: 1

image:
  registry: ghcr.io/chris99plus
  repository: authentication_service
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

tenantServiceUrl: ""

db:
  host: ""
  port: 27017
  collection: authentication

annotations: {
  prometheus.io/port: "80",
  prometheus.io/scrape: "true",
  prometheus.io/path: "/swagger-stats/metrics"
}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
