apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-transaction-service
  #namespace: free
  annotations:
    prometheus.io/port: "4000"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/swagger-stats/metrics"
spec:
  selector:
    matchLabels:
      app: transaction-service
  replicas: 2
  template:
    metadata:
      labels:
        app: transaction-service
      annotations:
        prometheus.io/port: "4000"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/swagger-stats/metrics"
    spec:
      containers:
        - name: transaction-service
          image: transaction-service
          ports:
            - containerPort: 4000
          imagePullPolicy: Never # Image should not be pulled
          env:
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: transactions-service-envs
                  key: mongodbConnectionString
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: transactions-service-envs
                  key: serverPort