apiVersion: v1
kind: Pod
metadata:
  name: pod-transaction-service
  annotations:
    prometheus.io/port: "4000"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/swagger-stats/metrics"
spec:
  containers:
    - name: transaction-service
      image: transaction-service
      ports:
        - containerPort: 4000
      imagePullPolicy: Never # Image should not be pulled
      env:
        - name: MONGODB_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: transactions-service-envs
              key: mongodbConnectionString
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: transactions-service-envs
              key: serverPort
