apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  #namespace: free
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '4000'
      prometheus.io/path: "/swagger-stats/metrics"
spec:
  selector:
    app: transaction-service
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31000