apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-control

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-control-role
rules:
- apiGroups: ["*"] 
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-control-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-control-role
subjects:
- kind: ServiceAccount
  name: cluster-control
  namespace: {{ .Release.Namespace }}
