name: Apply terraform on Azure

on: [workflow_dispatch]

run-name: Apply terraform on Azure

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: azure/setup-helm@v3
        name: Setup helm
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install

      - name: Helm build
        run: |
          helm dependency build
          
        working-directory: ./infrastructure/charts/budget-tracker
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"
          TF_VAR_AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          TF_VAR_REGISTRY_USERNAME: "${{ github.repository_owner }}"
          TF_VAR_REGISTRY_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
          TF_VAR_REGISTRY_SERVER: "${{ secrets.REGISTRY_SERVER }}"
          TF_VAR_REGISTRY_EMAIL: "${{ secrets.REGISTRY_EMAIL }}"
          TF_VAR_HETZNER_TOKEN: "${{ secrets.HETZNER_TOKEN }}"
          TF_VAR_HETZNER_DNS_ZONE_ID: "${{ secrets.HETZNER_DNS_ZONE_ID }}"

        working-directory: ./infrastructure/terraform
        shell: bash

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -out tf.plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"
          TF_VAR_AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          TF_VAR_REGISTRY_USERNAME: "${{ github.repository_owner }}"
          TF_VAR_REGISTRY_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
          TF_VAR_REGISTRY_SERVER: "${{ secrets.REGISTRY_SERVER }}"
          TF_VAR_REGISTRY_EMAIL: "${{ secrets.REGISTRY_EMAIL }}"
          TF_VAR_HETZNER_TOKEN: "${{ secrets.HETZNER_TOKEN }}"
          TF_VAR_HETZNER_DNS_ZONE_ID: "${{ secrets.HETZNER_DNS_ZONE_ID }}"

        working-directory: ./infrastructure/terraform
        shell: bash

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -input=false -no-color -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"
          TF_VAR_AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          TF_VAR_REGISTRY_USERNAME: "${{ github.repository_owner }}"
          TF_VAR_REGISTRY_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
          TF_VAR_REGISTRY_SERVER: "${{ secrets.REGISTRY_SERVER }}"
          TF_VAR_REGISTRY_EMAIL: "${{ secrets.REGISTRY_EMAIL }}"
          TF_VAR_HETZNER_TOKEN: "${{ secrets.HETZNER_TOKEN }}"
          TF_VAR_HETZNER_DNS_ZONE_ID: "${{ secrets.HETZNER_DNS_ZONE_ID }}"

        working-directory: ./infrastructure/terraform
        shell: bash
