name: build frontend

on:
  pull_request:
    paths:
      - frontend/**
  push:
    branches:
      - main
  workflow_dispatch:

run-name: Build frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: frontend/Dockerfile
          tags: ghcr.io/chris99plus/frontend:latest
          push: ${{ github.ref == 'refs/heads/main' }}
