name: Plan terraform on Azure

on:
  pull_request:
    paths:
      - infrastructure/**
  workflow_dispatch:


run-name: Plan terraform on Azure

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"
          TF_VAR_AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          TF_VAR_REGISTRY_USERNAME: "${{ github.repository_owner }}"
          TF_VAR_REGISTRY_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
          TF_VAR_REGISTRY_SERVER: "${{ secrets.REGISTRY_SERVER }}"
          TF_VAR_REGISTRY_EMAIL: "${{ secrets.REGISTRY_EMAIL }}"
          TF_VAR_HETZNER_TOKEN: "${{ secrets.HETZNER_TOKEN }}"
          TF_VAR_HETZNER_DNS_ZONE_ID: "${{ secrets.HETZNER_DNS_ZONE_ID }}"

        working-directory: ./infrastructure/terraform
        shell: bash

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -out tf.plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_AD_TENANT_ID }}"
          TF_VAR_AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          TF_VAR_REGISTRY_USERNAME: "${{ github.repository_owner }}"
          TF_VAR_REGISTRY_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
          TF_VAR_REGISTRY_SERVER: "${{ secrets.REGISTRY_SERVER }}"
          TF_VAR_REGISTRY_EMAIL: "${{ secrets.REGISTRY_EMAIL }}"
          TF_VAR_HETZNER_TOKEN: "${{ secrets.HETZNER_TOKEN }}"
          TF_VAR_HETZNER_DNS_ZONE_ID: "${{ secrets.HETZNER_DNS_ZONE_ID }}"

        working-directory: ./infrastructure/terraform
        shell: bash
