{{- if .Values.tenantSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenant.secretName" . }}
  labels:
    {{- include "tenant.labels" . | nindent 4 }}
type: Opaque
data:
  jwtSecret: {{ .Values.tenantSecret.jwtSecret | b64enc | quote }}
{{- end -}}