apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    {{- include "tenant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ .Values.frontendService.name }}.{{ .Values.frontendService.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    {{- include "tenant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ .Values.authenticationService.name }}.{{ .Values.authenticationService.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
